#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

MARKER = "OSD_STICK_OVERLAY_KISS_X_SUBPOSITIONS"

DEFS_RE = re.compile(
    r"(#define OSD_STICK_OVERLAY_WIDTH 7\n"
    r"#define OSD_STICK_OVERLAY_HEIGHT 5\n"
    r"#define OSD_STICK_OVERLAY_SPRITE_HEIGHT 3\n"
    r"#define OSD_STICK_OVERLAY_VERTICAL_POSITIONS \(OSD_STICK_OVERLAY_HEIGHT \* OSD_STICK_OVERLAY_SPRITE_HEIGHT\)\n)"
)

EXTRA_DEFS = r'''\1
// Custom OSD v1: KISS-style high-resolution stick cursor for analog MAX7456.
// Type 1 remains the stock Betaflight overlay.
// Type 2 uses 24 custom glyphs (0xA0-0xB7) generated by make_kiss_stick_font.py.
#define OSD_STICK_OVERLAY_KISS_X_SUBPOSITIONS 4
#define OSD_STICK_OVERLAY_KISS_Y_SUBPOSITIONS 6
#define OSD_STICK_OVERLAY_KISS_GLYPH_BASE 0xA0
#define OSD_STICK_OVERLAY_KISS_HORIZONTAL_POSITIONS (OSD_STICK_OVERLAY_WIDTH * OSD_STICK_OVERLAY_KISS_X_SUBPOSITIONS)
#define OSD_STICK_OVERLAY_KISS_VERTICAL_POSITIONS (OSD_STICK_OVERLAY_HEIGHT * OSD_STICK_OVERLAY_KISS_Y_SUBPOSITIONS)
'''

FUNC_RE = re.compile(
    r"static void osdElementStickOverlay\(osdElementParms_t \*element\)\n"
    r"\{.*?\n\}\n#endif // USE_OSD_STICK_OVERLAY",
    re.S,
)

NEW_FUNC = r'''static void osdElementStickOverlay(osdElementParms_t *element)
{
    rc_alias_e vertical_channel, horizontal_channel;

    if (element->item == OSD_STICK_OVERLAY_LEFT) {
        vertical_channel = radioModes[osdConfig()->overlay_radio_mode-1].left_vertical;
        horizontal_channel = radioModes[osdConfig()->overlay_radio_mode-1].left_horizontal;
    } else {
        vertical_channel = radioModes[osdConfig()->overlay_radio_mode-1].right_vertical;
        horizontal_channel = radioModes[osdConfig()->overlay_radio_mode-1].right_horizontal;
    }

    // Type 2: KISS-style sub-cell cursor on analog MAX7456.
    // The display is still character based, but the cursor glyph itself contains
    // one of 4 horizontal x 6 vertical dot positions inside a character cell.
    // This raises effective cursor resolution from 7x15 to 28x30 positions.
    if (element->type == OSD_ELEMENT_TYPE_2 &&
        element->osdDisplayPort->deviceType == DISPLAYPORT_DEVICE_TYPE_MAX7456) {
        const uint8_t fineX = scaleRange(
            constrain(rcData[horizontal_channel], PWM_RANGE_MIN, PWM_RANGE_MAX - 1),
            PWM_RANGE_MIN, PWM_RANGE_MAX,
            0, OSD_STICK_OVERLAY_KISS_HORIZONTAL_POSITIONS);
        const uint8_t fineY = OSD_STICK_OVERLAY_KISS_VERTICAL_POSITIONS - 1 - scaleRange(
            constrain(rcData[vertical_channel], PWM_RANGE_MIN, PWM_RANGE_MAX - 1),
            PWM_RANGE_MIN, PWM_RANGE_MAX,
            0, OSD_STICK_OVERLAY_KISS_VERTICAL_POSITIONS);

        const uint8_t subX = fineX % OSD_STICK_OVERLAY_KISS_X_SUBPOSITIONS;
        const uint8_t subY = fineY % OSD_STICK_OVERLAY_KISS_Y_SUBPOSITIONS;
        const uint8_t spriteIndex = subY * OSD_STICK_OVERLAY_KISS_X_SUBPOSITIONS + subX;

        element->buff[0] = OSD_STICK_OVERLAY_KISS_GLYPH_BASE + spriteIndex;
        element->buff[1] = '\0';
        element->elemOffsetX = fineX / OSD_STICK_OVERLAY_KISS_X_SUBPOSITIONS;
        element->elemOffsetY = fineY / OSD_STICK_OVERLAY_KISS_Y_SUBPOSITIONS;
        return;
    }

    // Type 1, and all non-MAX7456 displays (including MSP DisplayPort / DJI O4),
    // retain Betaflight's stock cursor so this patch is safe without the custom font.
    const uint8_t cursorX = scaleRange(constrain(rcData[horizontal_channel], PWM_RANGE_MIN, PWM_RANGE_MAX - 1), PWM_RANGE_MIN, PWM_RANGE_MAX, 0, OSD_STICK_OVERLAY_WIDTH);
    const uint8_t cursorY = OSD_STICK_OVERLAY_VERTICAL_POSITIONS - 1 - scaleRange(constrain(rcData[vertical_channel], PWM_RANGE_MIN, PWM_RANGE_MAX - 1), PWM_RANGE_MIN, PWM_RANGE_MAX, 0, OSD_STICK_OVERLAY_VERTICAL_POSITIONS);

    const char cursor = SYM_STICK_OVERLAY_SPRITE_HIGH + (cursorY % OSD_STICK_OVERLAY_SPRITE_HEIGHT);

    tfp_sprintf(element->buff, "%c", cursor);
    element->elemOffsetX = cursorX;
    element->elemOffsetY = cursorY / OSD_STICK_OVERLAY_SPRITE_HEIGHT;
}
#endif // USE_OSD_STICK_OVERLAY'''


def main():
    ap = argparse.ArgumentParser(description="Patch Betaflight with a KISS-style analog stick overlay variant")
    ap.add_argument("betaflight_root", type=Path, help="Path to the Betaflight source tree")
    args = ap.parse_args()

    path = args.betaflight_root / "src/main/osd/osd_elements.c"
    if not path.exists():
        raise SystemExit(f"Not found: {path}")

    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        print("Already patched; nothing to do.")
        return

    text2, n_defs = DEFS_RE.subn(EXTRA_DEFS, text, count=1)
    if n_defs != 1:
        raise SystemExit("Could not find the stock stick-overlay #define block. Betaflight source layout may have changed.")

    text3, n_func = FUNC_RE.subn(NEW_FUNC, text2, count=1)
    if n_func != 1:
        raise SystemExit("Could not find osdElementStickOverlay(). Betaflight source layout may have changed.")

    backup = path.with_suffix(path.suffix + ".pre-kiss-v1")
    backup.write_text(text, encoding="utf-8")
    path.write_text(text3, encoding="utf-8")
    print(f"Patched: {path}")
    print(f"Backup : {backup}")
    print("Type 1 = stock; Type 2 + MAX7456 = 28x30 KISS-style cursor.")

if __name__ == "__main__":
    main()
